# We need the CUDA base dockerfile to enable GPU rendering
# on hosts with GPUs.
# The image below is a pinned version of nvidia/cuda:9.1-cudnn7-devel-ubuntu16.04 (from Jan 2018)
# If updating the base image, be sure to test on GPU since it has broken in the past.
#FROM nvidia/cuda:10.1-cudnn7-devel-ubuntu16.04
#FROM nvidia/cuda:12.9.0-cudnn-devel-ubuntu22.04
FROM nvidia/cuda:12.8.0-cudnn-devel-ubuntu22.04

SHELL ["/bin/bash", "-c"]

##########################################################
### System dependencies
##########################################################
RUN apt-get update -q \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    cmake \
    curl \
    git \
    ffmpeg \
    libgl1-mesa-dev \
    libgl1-mesa-glx \
    libglew-dev \
    libosmesa6-dev \
    net-tools \
    software-properties-common \
    swig \
    unzip \
    vim \
    wget \
    xpra \
    xserver-xorg-dev \
    zlib1g-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV LANG C.UTF-8

# 确保 /home/junda 存在并归属 junda 用户
# RUN mkdir -p /home/junda && chown -R junda:junda /home/junda
RUN useradd -m -d /home/junda -s /bin/bash junda && \
    chown -R junda:junda /home/junda
# 切换到 junda 用户
USER junda
WORKDIR /home/junda

# 复制文件到 junda 的家目录（保持所有权）
COPY --chown=junda:junda ./azure/files/Xdummy /usr/local/bin/Xdummy
RUN chmod +x /usr/local/bin/Xdummy

# Workaround for NVIDIA GLVND issue
COPY --chown=junda:junda ./azure/files/10_nvidia.json /usr/share/glvnd/egl_vendor.d/10_nvidia.json
COPY --chown=junda:junda ./environment.yml /home/junda/environment.yml

ENV LD_LIBRARY_PATH /usr/local/nvidia/lib64:${LD_LIBRARY_PATH}

##########################################################
### gsutil (安装到 junda 的家目录)
##########################################################
RUN curl -sSL https://sdk.cloud.google.com | bash
ENV PATH $PATH:/home/junda/google-cloud-sdk/bin

##########################################################
### MuJoCo (安装到 junda 的家目录)
##########################################################
RUN mkdir -p /home/junda/.mujoco \
    && wget https://www.roboti.us/download/mujoco200_linux.zip -O mujoco.zip \
    && unzip mujoco.zip -d /home/junda/.mujoco \
    && rm mujoco.zip
RUN mkdir -p /home/junda/.mujoco \
    && wget https://www.roboti.us/download/mjpro150_linux.zip -O mujoco.zip \
    && unzip mujoco.zip -d /home/junda/.mujoco \
    && rm mujoco.zip
RUN ln -s /home/junda/.mujoco/mujoco200_linux /home/junda/.mujoco/mujoco200
ENV LD_LIBRARY_PATH /home/junda/.mujoco/mjpro150/bin:${LD_LIBRARY_PATH}
ENV LD_LIBRARY_PATH /home/junda/.mujoco/mujoco200/bin:${LD_LIBRARY_PATH}
ENV LD_LIBRARY_PATH /home/junda/.mujoco/mujoco200_linux/bin:${LD_LIBRARY_PATH}
COPY --chown=junda:junda ./azure/files/mjkey.txt /home/junda/.mujoco

##########################################################
### Conda (安装到 /home/junda/miniconda3)
##########################################################
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /tmp/miniconda.sh && \
    bash /tmp/miniconda.sh -b -p /home/junda/miniconda3 && \
    rm /tmp/miniconda.sh && \
    echo "export PATH=/home/junda/miniconda3/bin:\$PATH" >> /home/junda/.bashrc && \
    echo "source /home/junda/miniconda3/etc/profile.d/conda.sh" >> /home/junda/.bashrc

ENV PATH /home/junda/miniconda3/bin:$PATH

RUN conda update -y --name base conda && conda clean --all -y

RUN git config --global url."https://".insteadOf git://
RUN conda env create -f /home/junda/environment.yml 
    # --quiet && \
    #conda run -n diffuser conda install --no-deps gym==0.18.0 && \
    #conda run -n diffuser pip install git+https://github.com/JannerM/doodad.git@janner

ENV PATH /home/junda/miniconda3/envs/diffusion/bin:$PATH

##########################################################
### patchelf
##########################################################
#RUN curl -o /usr/local/bin/patchelf https://s3-us-west-2.amazonaws.com/openai-sci-artifacts/manual-builds/patchelf_0.9_amd64.elf \
#    && chmod +x /usr/local/bin/patchelf

# 设置环境变量
RUN echo "source activate /home/junda/miniconda3/envs/diffuser" >> /home/junda/.bashrc && \
    echo "export MUJOCO_PY_MUJOCO_PATH=/home/junda/.mujoco/mujoco200_linux" >> /home/junda/.bashrc && \
    echo "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/junda/.mujoco/mujoco200_linux/bin" >> /home/junda/.bashrc && \
    export "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/junda/.mujoco/mjpro150/bin" >> /home/junda/.bashrc && \
    echo "export PYTHONPATH=\$PYTHONPATH:/home/code" >> /home/junda/.bashrc && \
    echo "export CUDA_VISIBLE_DEVICES=0" >> /home/junda/.bashrc

# 确保 .bashrc 生效
SHELL ["/bin/bash", "--login", "-c"]
